### ISSUE TITLE
Failed to acquire interface: omni::kit::IApp (pluginName: nullptr)

### ISSUE THREAD

**Issue by vinci0007** [NVIDIA-Omniverse/OmniIsaacGymEnvs#175]
### **_Describe  Bug_**:

- When I use conda env to run some isaac-sim DEMO, it cannot work.

### **System Info**

1. WINDOWS 11 + Anaconda 3 + Python 3.10
2. Isaac Sim Version: 4.1.0
3. CUDA: 12.1
4. GPU Driver: 560.94 and 550
5. 

**### LOGs**

[Warning] [omni.isaac.kit.simulation_app] Modules: ['omni.kit_app'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Traceback (most recent call last):
  File "E:\0001_Work_New\005_YangGu\0001_ROBOT\00004_RobotSim2Real\Isaacsim\work\env_test.py", line 70, in <module>
    env = SimulationApp()
  File "D:\Documents\VirtualMachineOS\Anaconda\envs\isaac_linux\Lib\site-packages\isaacsim\exts\omni.isaac.kit\omni\isaac\kit\simulation_app.py", line 198, in __init__
    self._app = omni.kit.app.get_app()
  File "D:\Documents\VirtualMachineOS\Anaconda\envs\isaac_linux\Lib\site-packages\omni\kernel\py\omni\kit\app\_impl\app_iface.py", line 19, in get_app
    return get_app_interface()
  File "D:\Documents\VirtualMachineOS\Anaconda\envs\isaac_linux\Lib\site-packages\omni\kernel\py\omni\kit\app\_impl\app_iface.py", line 14, in get_app_interface
    return acquire_app_interface()
RuntimeError: Failed to acquire interface: omni::kit::IApp (pluginName: nullptr)

Checklist
 

+ [x] I have checked that there is no similar issue in the repo (required)

 

+ [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by vinci0007** [comment]
report in isaac_lab , so close this
