### ISSUE TITLE
[Error] There was an error when I runned examples

### ISSUE THREAD

**Issue by PARKBONG** [NVIDIA-Omniverse/OmniIsaacGymEnvs#6]
After Installation, I tried to launch `rlgames_train.py`

`~/OmniIsaacGymEnvs/omniisaacgymenvs$ PYTHON_PATH scripts/rlgames_train.py task=Cartpole`

But here is error:

> Traceback (most recent call last):
>   File "scripts/rlgames_train.py", line 34, in <module>
>     from omniisaacgymenvs.utils.config_utils.path_utils import retrieve_checkpoint_path
>   File "\~/OmniIsaacGymEnvs/omniisaacgymenvs/utils/config_utils/path_utils.py", line 32, in <module>
>     import omni.client
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/extscore/omni.client/omni/client/__init__.py", line 21, in <module>
>     from ._omniclient import *
> ImportError: ~ /.local/share/ov/pkg/isaac_sim-2022.1.0/kit/extscore/omni.usd.libs/bin/libjs.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__18Tf_PostErrorHelperERKNS_13TfCallContextENS_16TfDiagnosticTypeEPKcz
> There was an error running python

So I tested the simplest code
**Print_pi.py**
```
from omni.isaac.examples.hello_world.hello_world_extension import HelloWorldExtension
print('Hi")
```
**Run**
`$ PYTHON_PATH print_hi.py`

**ERROR**

> Traceback (most recent call last):
>   File "print_hi.py", line 12, in <module>
>     from omni.isaac.examples.hello_world.hello_world_extension import HelloWorldExtension
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.examples/omni/isaac/examples/hello_world/__init__.py", line 10, in <module>
>     from omni.isaac.examples.hello_world.hello_world import HelloWorld
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.examples/omni/isaac/examples/hello_world/hello_world.py", line 9, in <module>
>     from omni.isaac.examples.base_sample import BaseSample
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.examples/omni/isaac/examples/base_sample/__init__.py", line 10, in <module>
>     from omni.isaac.examples.base_sample.base_sample import BaseSample
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.examples/omni/isaac/examples/base_sample/base_sample.py", line 9, in <module>
>     from omni.isaac.core import World
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.core/omni/isaac/core/__init__.py", line 9, in <module>
>     from omni.isaac.core.physics_context.physics_context import PhysicsContext
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.core/omni/isaac/core/physics_context/__init__.py", line 9, in <module>
>     from omni.isaac.core.physics_context.physics_context import PhysicsContext
>   File "\~/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.core/omni/isaac/core/physics_context/physics_context.py", line 12, in <module>
>     from pxr import Usd, UsdGeom, Gf, Sdf, UsdPhysics, PhysxSchema, UsdShade
>   File "~/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/extscore/omni.usd.libs/pxr/Usd/__init__.py", line 24, in <module>
>     from . import bong_usd
> ImportError: ~/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/extscore/omni.usd.libs/bin/libjs.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__18Tf_PostErrorHelperERKNS_13TfCallContextENS_16TfDiagnosticTypeEPKcz
> There was an error running python

How can I solve it?

**Here's my hardware spec**
Ubuntu 20.04
Python 3.8 (I tried Python 3.7 in conda env, but I got the same result)
Intel CPU + RTX3070Ti

**Comment by kellyguo11** [comment]
Hi @PARKBONG 

I think this [thread ](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/issues/2) might be relevant. We need to move the omni.client import to after VecEnv class gets created.
