### ISSUE TITLE
Error when changing the number of environments

### ISSUE THREAD

**Issue by AshWYL** [NVIDIA-Omniverse/OmniIsaacGymEnvs#7]
Hi,

Thank you for your work！

Runs with an error when I make changes to the number of environments, whether the number of environments is larger or less than the default number, for example:

`PYTHON_PATH scripts/rlgames_train.py task=Cartpole num_envs=64`

I got this:

> Error executing job with overrides: ['task=Cartpole', 'num_envs=64']
> Traceback (most recent call last):
>   File "scripts/rlgames_train.py", line 109, in parse_hydra_configs
>     rlg_trainer.run()
>   File "scripts/rlgames_train.py", line 82, in run
>     'sigma': None
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/torch_runner.py", line 108, in run
>     self.run_train(args)
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/torch_runner.py", line 86, in run_train
>     agent = self.algo_factory.create(self.algo_name, base_name='run', params=self.params)
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/common/object_factory.py", line 15, in create
>     return builder(**kwargs)
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/torch_runner.py", line 37, in <lambda>
>     self.algo_factory.register_builder('a2c_continuous', lambda **kwargs : a2c_continuous.A2CAgent(**kwargs))
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/algos_torch/a2c_continuous.py", line 18, in __init__
>     a2c_common.ContinuousA2CBase.__init__(self, base_name, params)
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/common/a2c_common.py", line 965, in __init__
>     A2CBase.__init__(self, base_name, params)
>   File "/home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/lib/python3.7/site-packages/rl_games/common/a2c_common.py", line 185, in __init__
>     assert(self.batch_size % self.minibatch_size == 0)
> AssertionError
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> /home/jrl/.local/share/ov/pkg/isaac_sim-2022.1.0/python.sh: line 46:  8605 Segmentation fault      (core dumped) $python_exe "$@" $args

Since I set a smaller number of environments, it seems that the problem is not related to memory.
Can you give me some advice?

**Comment by AshWYL** [comment]
The problem has been solved by referring to the following document：

> rl-games requires minibatch_size defined in the training config to be a factor of horizon_length * num_envs. If this is not the case, you may see an assertion error assert(self.batch_size % self.minibatch_size == 0). Please adjust the parameters in the training config yaml file accordingly.
